services:
  app:
    build: .
    container_name: reports_cli_app
    command: ["php", "reports-cli", "run"]

  test:
    build: .
    container_name: reports_cli_test
    command: ["./vendor/bin/pest"] 
